import Link from 'next/link';
import {ArrowRight,MapPin,ChevronRight} from 'lucide-react';
import {api,selectedStore,ApiError} from '@/lib/upstream';
import {list,unwrap,product,Json} from '@/lib/types';
import {content} from '@/config/content';
import {Photo,Empty} from '@/components/ui';
import {ProductGrid,ProductDetail} from '@/components/products';
import {Filters} from '@/components/filters';
import {LoyaltyCard,Reviews} from './user-pages';
export function SectionHeading({title,href,subtitle}:{title:string;href?:string;subtitle?:string}){return <div className="section-heading"><div>{subtitle&&<p className="eyebrow">{subtitle}</p>}<h2>{title}</h2></div>{href&&<Link href={href}>Смотреть всё <ArrowRight size={18}/></Link>}</div>;}
export async function Home(){const id=await selectedStore();const [groups,categories,homeCategories,banners,stories]=await Promise.all([api(`stores/${id}/product-groups`).then(list),api(`stores/${id}/categories`).then(list),api(`stores/${id}/categories/home`).then(list),api(`stores/${id}/banners`).then(list),api('stories').then(list)]);const recommended=groups.filter(g=>g.is_recommended);const featured=groups.find(g=>g.slug==='firmennye-bliuda')||groups.find(g=>!g.is_recommended&&g.productsCount>0);const products=featured?list(await api(`product-groups/${featured.id}/products?storeId=${id}&perPage=8`)).map(product):[];const showcase=homeCategories.length?homeCategories:categories.slice(0,6);return <><section className="welcome"><div><p className="eyebrow">{content.brand}</p><h1>{content.tagline}</h1><p>Продукты для любимых блюд.<br className="mobile-break"/> И маленьких повседневных радостей.</p><Link href="/addresses" className="address-cta"><MapPin size={18}/> Указать адрес доставки <ChevronRight size={16}/></Link></div><LoyaltyCard compact/></section>{stories.length>0&&<div className="stories">{stories.map(st=><Link href={'/stories/'+st.id} key={st.id}><Photo src={st.image?.path||st.preview?.path} alt={st.title}/><span>{st.title}</span></Link>)}</div>}{content.home.sections.map(section=>{if(section==='collections')return <section key={section}><SectionHeading title={content.home.titles.collections} subtitle="Собрали для вас"/><div className="collections">{recommended.map((g,i)=><Link key={g.id} href={'/collection/'+g.slug} className={`collection-tile tone-${i%5}`}><Photo src={g.image?.path} alt=""/><strong>{g.title}</strong><span className="tile-arrow"><ArrowRight size={18}/></span></Link>)}</div></section>;if(section==='banners')return banners.length?<section className="banner-grid" key={section}>{banners.map(b=>{const href=b.linkType==='product'&&b.linkProductId?'/product/'+b.linkProductId:b.linkType==='category'&&b.linkCategoryId?'/category/'+b.linkCategoryId:null;return href?<Link href={href} key={b.id}><Photo src={b.image?.path} alt={b.title}/></Link>:<Photo key={b.id} src={b.image?.path} alt={b.title}/>;})}</section>:null;if(section==='featured')return products.length?<section key={section}><SectionHeading title={featured.title} href={'/collection/'+featured.slug} subtitle="Приготовлено с заботой"/><ProductGrid products={products}/></section>:null;return <section key={section} className="category-sections"><SectionHeading title={content.home.titles.categories} href="/catalog"/><CategoryTiles categories={showcase}/></section>;})}</>;}
export function CategoryTiles({categories}:{categories:Json[]}){return <div className="category-tiles">{categories.map((c,i)=><Link className={`category-tile tone-${i%5}`} href={'/category/'+c.id} key={c.id}>{c.image?.path&&<Photo src={c.image.path} alt=""/>}<strong>{c.name}</strong><ArrowRight size={20}/></Link>)}</div>;}
function queryString(params:Record<string,string|string[]|undefined>){const q=new URLSearchParams();for(const [k,v] of Object.entries(params))if(typeof v==='string'&&(/^(page|query|sort|priceMin|priceMax|onlyDiscounted|sugarFree|categoryId|brandId)$/.test(k)||/^filter\[[a-zA-Z0-9_-]+\]$/.test(k)))q.set(k,v);q.set('perPage',String(content.pageSize));return q;}
export async function Catalog({kind,id,params}:{kind:string;id?:string;params:Record<string,string|string[]|undefined>}){const store=await selectedStore(),q=queryString(params);let title='Каталог',data:Json,children:Json[]=[],filters:Json=null;const categories=list(await api(`stores/${store}/categories`));if(kind==='search'){title=params.query?`Результаты поиска «${params.query}»`:'Найдётся всё, что нужно';if(typeof params.query!=='string'||params.query.trim().length<2)return <><h1>{title}</h1><form className="large-search" action="/search"><input name="query" placeholder="Например, молоко" minLength={2} required aria-label="Поиск"/><button className="primary">Найти</button></form><CategoryTiles categories={categories}/></>;[data,filters]=await Promise.all([api(`search/stores/${store}/products?${q}`),api(`search/stores/${store}/filters?${q}`)]);}else if(kind==='collection'){const groups=list(await api(`stores/${store}/product-groups`));const group=groups.find(g=>g.slug===id||String(g.id)===id);if(!group)throw new ApiError(404,{message:'Подборка не найдена'});title=group.title;data=await api(`stores/${store}/product-groups/slug/${encodeURIComponent(group.slug)}/products?${q}`);}else{const category=id||'0';if(id){let c=categories.find(c=>String(c.id)===id);if(!c){const all=await Promise.all(categories.map(c=>api(`stores/${store}/categories/${c.id}/children`).then(list)));c=all.flat().find(c=>String(c.id)===id);}title=c?.name||'Товары категории';children=list(await api(`stores/${store}/categories/${category}/children`));}else children=categories;[data,filters]=await Promise.all([api(`stores/${store}/categories/${category}/products?${q}`),api(`stores/${store}/categories/${category}/filters`)]);}
const products=list(data).map(product),page=Math.max(1,Number(params.page)||1);function pageLink(n:number){const p=new URLSearchParams(q);p.set('page',String(n));p.delete('perPage');return '?'+p;}
return <><div className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><Link href="/catalog">Каталог</Link>{kind!=='catalog'&&<><span>/</span><span>{title}</span></>}</div><div className="page-heading"><h1>{title}</h1>{typeof data.total==='number'&&<span className="muted">{data.total.toLocaleString('ru-RU')} товаров</span>}</div>{children.length>0&&<CategoryTiles categories={children}/>}<div className="catalog-layout"><Filters filters={unwrap(filters)}/><div>{products.length?<ProductGrid products={products}/>:<Empty title="Ничего не нашлось"><p>Попробуйте изменить запрос или сбросить фильтры.</p></Empty>}<nav className="pagination" aria-label="Страницы каталога">{page>1&&<Link className="secondary" href={pageLink(page-1)}>← Назад</Link>}<span>Страница {page}</span>{data.hasMore&&<Link className="primary" href={pageLink(page+1)}>Далее →</Link>}</nav></div></div></>;}
export async function ProductPage({id}:{id:string}){const store=await selectedStore();const p=product(unwrap(await api(`products/${encodeURIComponent(id)}?storeId=${store}`)));const [similar,relatedGroups]=await Promise.all([api(`products/${id}/similar?storeId=${store}&perPage=6`).then(list),api(`products/${id}/related?storeId=${store}&perPage=6`).then(list)]);const related=relatedGroups.flatMap(group=>Array.isArray(group.products)?group.products:[group]).filter(v=>v?.title&&v?.price!=null);return <><div className="breadcrumbs"><Link href="/catalog">Каталог</Link><span>/</span><span>{p.title}</span></div><ProductDetail p={p}/><Reviews productId={p.id}/>{similar.length>0&&<section><SectionHeading title="Вам может понравиться"/><ProductGrid products={similar.slice(0,6).map(product)}/></section>}{related.length>0&&<section><SectionHeading title="Хорошо сочетается"/><ProductGrid products={related.slice(0,6).map(product)}/></section>}</>;}
