'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState,useEffect} from 'react';
import {MapPin,Search,Heart,UserRound,ShoppingBasket,House,LayoutGrid,Bell,ChevronDown} from 'lucide-react';
import {useShop} from './shop-context';
import {request} from '@/lib/client';
import {list,Json,money} from '@/lib/types';
import {Modal} from './ui';
export function Header({store}:{store:Json}){const s=useShop(),router=useRouter(),path=usePathname();const [choose,setChoose]=useState(false),[stores,setStores]=useState<Json[]>([]),[busy,setBusy]=useState(false);const items=s.cart?.storeGroups?.flatMap((g:Json)=>g.items)||s.cart?.dateGroups?.flatMap((g:Json)=>g.items)||[];const total=s.cart?.totalToPay;const nav=[{href:'/',title:'Главная',Icon:House},{href:'/catalog',title:'Каталог',Icon:LayoutGrid},{href:'/favorites',title:'Избранное',Icon:Heart},{href:'/profile',title:'Профиль',Icon:UserRound}];
async function open(){setChoose(true);await s.run(async()=>setStores(list(await request('stores'))));}
async function change(id:number){setBusy(true);await s.run(async()=>{await request('/api/store','POST',{storeId:id});await s.refresh();setChoose(false);s.notice('Магазин изменён. Проверьте обновлённый состав корзины.');router.refresh();});setBusy(false);}
return <><div className="topline"><div className="container"><span>Продукты и всё необходимое с доставкой</span><Link href="/faq">Помощь и ответы на вопросы ↗</Link></div></div><header className="header"><div className="container header-row"><Link href="/" className="brand"><img src="/images/logo.webp" alt=""/><span>Ласточка<small>Джами</small></span></Link><Link className="catalog-button" href="/catalog"><LayoutGrid size={20}/> Каталог</Link><SearchBox/><button className="location" onClick={open}><MapPin size={21}/><span><small>Ваш магазин</small>{store?.name||'Выбрать магазин'}</span><ChevronDown size={15}/></button><Link className="header-action" href="/profile"><UserRound/><span>Профиль</span></Link><Link className="cart-button" href="/cart"><ShoppingBasket/><span>{typeof total==='number'?money(total):'Корзина'}{items.length>0&&<small>{items.length} поз.</small>}</span></Link></div><div className="container mobile-address"><button onClick={open}><MapPin size={17}/>{store?.name||'Выберите магазин'}<ChevronDown size={15}/></button><Link href="/addresses">Указать адрес →</Link><Link href="/notifications" aria-label="Уведомления"><Bell size={19}/></Link></div></header><nav className="bottom-nav" aria-label="Основная навигация">{nav.map(({href,title,Icon})=><Link key={href} href={href} className={(href==='/'?path==='/':path.startsWith(href))?'active':''}><Icon size={21}/><span>{title}</span></Link>)}</nav><div className="float-actions"><Link href="/search"><Search size={18}/> Поиск</Link><Link href="/cart"><ShoppingBasket size={18}/>{typeof total==='number'?money(total):`Корзина${items.length?' · '+items.length:''}`}</Link></div>{choose&&<Modal title="Ваш магазин и адрес" onClose={()=>setChoose(false)}><p className="muted">Ассортимент и цены зависят от магазина. При смене недоступные товары могут быть удалены из корзины.</p><Link href="/addresses" className="primary block" onClick={()=>setChoose(false)}>Выбрать адрес доставки</Link><div className="stack">{stores.map(st=><button key={st.id} className="store-option" disabled={busy} onClick={()=>change(st.id)}><MapPin/><span><strong>{st.name}</strong><small>{st.address||'Адрес не указан'}</small></span>{store?.id===st.id&&'✓'}</button>)}</div></Modal>}</>;}
export function SearchBox(){const router=useRouter();const [q,setQ]=useState(''),[suggestions,setSuggestions]=useState<Json[]>([]);useEffect(()=>{if(q.trim().length<2){setSuggestions([]);return;}let active=true;const t=setTimeout(()=>{request('search/suggestions?query='+encodeURIComponent(q)).then(d=>{if(active)setSuggestions(list(d).slice(0,5));}).catch(()=>setSuggestions([]));},300);return()=>{active=false;clearTimeout(t);};},[q]);return <form className="search-box" action="/search" onSubmit={e=>{e.preventDefault();setSuggestions([]);router.push('/search?query='+encodeURIComponent(q));}}><Search size={21}/><input name="query" aria-label="Поиск товаров" placeholder="Найти любимые продукты" value={q} onChange={e=>setQ(e.target.value)} minLength={2}/><button aria-label="Найти" type="submit">→</button>{suggestions.length>0&&<div className="suggestions">{suggestions.map((v,i)=>{const text=typeof v==='string'?v:v.title||v.text||v.query;return text?<button key={i} type="button" onClick={()=>{setQ(text);setSuggestions([]);router.push('/search?query='+encodeURIComponent(text));}}>{text}</button>:null;})}</div>}</form>;}
