'use client';
import {createContext,useContext,useState,useEffect,ReactNode,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import {request,browserSession} from '@/lib/client';
import {Json,Product,step,unwrap} from '@/lib/types';
import {Modal,ErrorMessage} from './ui';
type Shop={authenticated:boolean;ready:boolean;cart:Json;refresh:()=>Promise<void>;login:()=>void;run:<T>(f:()=>Promise<T>)=>Promise<T|undefined>;notice:(s:string)=>void;add:(p:Product,supplements?:Json[])=>Promise<void>;setQuantity:(id:number,n:number)=>Promise<void>;logout:()=>Promise<void>;checkoutEnabled:boolean};
const Context=createContext<Shop>(null!);
export const useShop=()=>useContext(Context);
export function ShopProvider({children}:{children:ReactNode}){const router=useRouter();const [authenticated,setAuth]=useState(false),[ready,setReady]=useState(false),[cart,setCart]=useState<Json>(null),[authOpen,setAuthOpen]=useState(false),[message,setMessage]=useState(''),[checkoutEnabled,setCheckout]=useState(false);
const refresh=useCallback(async()=>{const s=await browserSession();setAuth(s.authenticated);setCheckout(s.checkoutEnabled);setReady(true);if(s.authenticated){try{setCart(unwrap(await request('cart')));}catch(e){setMessage((e as Error).message);}}else setCart(null);},[]);
useEffect(()=>{void refresh();},[refresh]);useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),6500);return()=>clearTimeout(t);},[message]);
async function run<T,>(f:()=>Promise<T>):Promise<T|undefined>{try{return await f();}catch(e){if((e as Json).status===401)setAuthOpen(true);else setMessage((e as Error).message);return undefined;}}
async function add(p:Product,supplements?:Json[]){if(!authenticated){setAuthOpen(true);return;}await run(async()=>{setCart(unwrap(await request('cart/items','POST',{productId:p.id,quantity:step(p),storeId:p.storeId,supplements})));setMessage('Товар добавлен в корзину');});}
async function setQuantity(id:number,n:number){await run(async()=>{await request(`cart/items/${id}`,n>0?'PUT':'DELETE',n>0?{quantity:n}:undefined);await refresh();});}
async function logout(){await run(async()=>{await request('auth/logout','POST');setAuth(false);setCart(null);await refresh();router.refresh();});}
return <Context.Provider value={{authenticated,ready,cart,refresh,login:()=>setAuthOpen(true),run,notice:setMessage,add,setQuantity,logout,checkoutEnabled}}>{children}{message&&<div className="toast" role="status" onClick={()=>setMessage('')}>{message}</div>}{authOpen&&<Login onClose={()=>setAuthOpen(false)} onSuccess={async()=>{setAuthOpen(false);await refresh();router.refresh();}}/>}</Context.Provider>;}
function Login({onClose,onSuccess}:{onClose:()=>void;onSuccess:()=>Promise<void>}){const [phone,setPhone]=useState('+7'),[code,setCode]=useState(''),[sent,setSent]=useState(false),[length,setLength]=useState(6),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resend,setResend]=useState(0);useEffect(()=>{if(resend<=0)return;const t=setTimeout(()=>setResend(resend-1),1000);return()=>clearTimeout(t);},[resend]);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const normalized='+7'+phone.replace(/\D/g,'').slice(-10);if(sent){await request('auth/phone-confirm','POST',{phone:normalized,code});await onSuccess();}else{const d=await request('auth/phone-login','POST',{phone:normalized,method:'sms'});setLength(d.codeLength||6);setSent(true);setResend(60);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <Modal title={sent?'Введите код из SMS':'Рады вас видеть'} onClose={onClose}><p className="muted">{sent?`Отправили код на ${phone}`:'Войдите, чтобы сохранять любимые товары, копить бонусы и оформлять заказы.'}</p><form className="stack" onSubmit={submit}>{!sent?<label>Номер телефона<input autoFocus type="tel" autoComplete="tel" required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+7 900 000-00-00" minLength={11}/></label>:<label>Код подтверждения<input autoFocus inputMode="numeric" autoComplete="one-time-code" pattern={`[0-9]{${length}}`} maxLength={length} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/></label>}{error&&<ErrorMessage message={error}/>}<button className="primary" disabled={busy}>{busy?'Подождите…':sent?'Войти':'Получить код'}</button>{sent&&<button type="button" className="text-button" disabled={resend>0} onClick={()=>{setSent(false);setCode('');}}>{resend>0?`Повторить через ${resend} с`:'Изменить номер или отправить код снова'}</button>}</form></Modal>;}
export function AuthGate({children,title='Войдите в аккаунт'}:{children:ReactNode;title?:string}){const s=useShop();if(!s.ready)return <p className="muted">Загружаем…</p>;return s.authenticated?<>{children}</>:<div className="auth-gate"><img src="/images/swallow.webp" alt=""/><h2>{title}</h2><p>Ваши покупки, адреса и бонусы будут доступны после входа.</p><button className="primary" onClick={s.login}>Войти по телефону</button></div>;}
